/** Help Center — structure mirrors faq.whatsapp.com-style layout */

export const sidebarCategories = [
  {
    id: 'get-started',
    label: 'Get Started',
    icon: 'flag',
    articles: [
      {
        id: 'download-installation',
        title: 'Download and Installation',
        href: '#download-installation',
        icon: 'download',
        subItems: [
          { title: 'How to download or uninstall WhatsApp', href: '/help-center/download-uninstall' },
          { title: 'About supported operating systems', href: '/help-center/supported-operating-systems' },
          { title: 'About supported devices', href: '/help-center/supported-devices' },
          { title: 'About rooted phones and custom ROMs', href: '/help-center/rooted-phones-custom-roms' },
          { title: 'Ending support for WhatsApp on KaiOS', href: '/help-center/ending-whatsapp-kaios' },
        ],
      },
      {
        id: 'registration',
        title: 'Registration',
        href: '#registration',
        icon: 'user',
        subItems: [
          { title: 'Parent-Managed Accounts', href: '/help-center/parent-managed-accounts' },
          { title: 'How to register your phone number', href: '/help-center/register-phone-number' },
          { title: 'How to verify your number by SMS', href: '/help-center/verify-your-number-by-sms' },
          { title: 'About registration and two-step verification', href: '/help-center/about-registration-two-step-verification' },
          { title: 'How to register your account with a phone call', href: '/help-center/register-account-with-phone-call' },
          { title: 'About automatic phone number verification', href: '/help-center/automatic-phone-number-verification' },
          { title: "Can't complete registration", href: '/help-center/cant-complete-registration' },
          { title: 'How to manage two-step verification settings', href: '/help-center/manage-two-step-verification-settings' },
          { title: 'How to reset your two-step verification PIN', href: '/help-center/reset-two-step-verification-pin' },
          {
            title: "Can't request another verification code without waiting",
            href: '/help-center/cant-request-another-verification-code-without-waiting',
          },
          { title: "I'm traveling and I can't get my WhatsApp code", href: '/help-center/traveling-cant-get-whatsapp-code' },
          { title: 'Received verification code without requesting it', href: '/help-center/received-verification-code-without-requesting' },
        ],
      },
      {
        id: 'linked-devices',
        title: 'Linked Devices',
        href: '#linked-devices',
        icon: 'card',
        subItems: [
          { title: 'About linked devices', href: '/help-center/about-linked-devices?platform=ios' },
          { title: 'How to link a device', href: '/help-center/how-to-link-a-device?platform=android' },
          { title: 'About message history on linked devices', href: '/help-center/about-message-history-on-linked-devices' },
          { title: 'About linking WhatsApp to a second phone', href: '/help-center/about-linking-whatsapp-to-a-second-phone?platform=android' },
          { title: 'About WhatsApp for desktops', href: '/help-center/about-whatsapp-for-desktops?platform=windows-desktop' },
          { title: 'About WhatsApp Web', href: '/help-center/about-whatsapp-web' },
          { title: 'About WhatsApp for iPad', href: '/help-center/about-whatsapp-for-ipad' },
          { title: 'About WhatsApp for Android tablets', href: '/help-center/about-whatsapp-for-android-tablets' },
          { title: 'About WhatsApp for Wear OS', href: '/help-center/about-whatsapp-for-wear-os' },
          { title: 'About WhatsApp on Meta Quest', href: '/help-center/about-whatsapp-on-meta-quest' },
          { title: 'How to link your Meta Quest', href: '/help-center/how-to-link-your-meta-quest?platform=android' },
          { title: 'About WhatsApp on Meta AI glasses', href: '/help-center/about-whatsapp-on-meta-ai-glasses' },
          { title: 'About WhatsApp for Apple Watch', href: '/help-center/about-whatsapp-for-apple-watch' },
          { title: 'About WhatsApp for Garmin Smartwatches', href: '/help-center/about-whatsapp-for-garmin-smartwatches' },
          { title: 'How to unlink a device', href: '/help-center/how-to-unlink-a-device?platform=android' },
          { title: 'How to download WhatsApp Desktop', href: '/help-center/how-to-download-whatsapp-desktop?platform=windows-desktop' },
          { title: 'About supported operating systems', href: '#ld-supported-operating-systems' },
          { title: 'How to switch accounts on WhatsApp', href: '/help-center/how-to-switch-accounts-on-whatsapp?platform=android' },
        ],
      },
      {
        id: 'get-started-troubleshooting',
        title: 'Troubleshooting',
        href: '#get-started-troubleshooting',
        icon: 'chat',
        subItems: [
          { title: 'Not seeing a feature on WhatsApp', href: '#gst-not-seeing-feature' },
          { title: 'Fixing issues on WhatsApp', href: '#gst-fixing-issues' },
          { title: 'How to fix connection issues', href: '/help-center/how-to-fix-connection-issues?platform=web' },
          { title: "Can't download or update WhatsApp", href: '/help-center/cant-download-update' },
          { title: 'How to change WhatsApp language', href: '/help-center/change-language' },
          { title: 'How to manually update WhatsApp', href: '#gst-manual-update' },
          { title: "Can't change phone number", href: '#gst-cant-change-number' },
          { title: "Can't log out of WhatsApp", href: '#gst-cant-logout' },
          { title: 'Contact names missing', href: '#gst-contact-names-missing' },
          { title: "Can't see a contact's profile information", href: '#gst-contact-profile-missing' },
          { title: 'How to recover lost contacts', href: '#gst-recover-contacts' },
          { title: "Don't recognize contact's account", href: '#gst-dont-recognize-contact' },
          { title: 'Seeing "Your devices were logged out"', href: '#gst-devices-logged-out' },
          { title: 'Seeing "You have been logged out"', href: '#gst-logged-out' },
          {
            title: 'Seeing "You have been logged out for your account security"',
            href: '#gst-logged-out-security',
          },
          { title: 'Seeing "Devices out of sync" message', href: '#gst-devices-out-of-sync' },
        ],
      },
      {
        id: 'contacts',
        title: 'Contacts',
        href: '#contacts',
        icon: 'userCircle',
        subItems: [
          { title: 'How to add, edit, or delete a contact', href: '#con-add-edit-delete-contact' },
          { title: 'How to find and invite contacts', href: '#con-find-invite-contacts' },
          { title: 'About WhatsApp contacts', href: '#con-about-contacts' },
          { title: 'About contact upload', href: '#con-contact-upload' },
          { title: 'About WhatsApp QR codes', href: '#con-about-qr-codes' },
          { title: 'How to scan a WhatsApp QR code', href: '#con-scan-qr' },
          { title: 'How to view your WhatsApp QR code', href: '#con-view-qr' },
          { title: 'How to reset your WhatsApp QR code', href: '#con-reset-qr' },
          { title: 'How to share your WhatsApp QR code', href: '#con-share-qr' },
          { title: 'How to edit favorites', href: '#con-edit-favorites' },
        ],
      },
      {
        id: 'status',
        title: 'Status',
        href: '#status',
        icon: 'broadcast',
        subItems: [
          { title: 'About status', href: '#st-about-status' },
          { title: 'How to create and share a status', href: '#st-create-share-status' },
          { title: 'How to see who viewed or liked your status', href: '#st-viewed-liked' },
          { title: 'How to view, like, and reply to status', href: '#st-view-like-reply' },
          { title: 'How to manage status privacy', href: '#st-status-privacy' },
          { title: 'How to share your WhatsApp Status to other apps', href: '#st-share-to-apps' },
          { title: 'How to hide and unhide statuses', href: '#st-hide-unhide' },
          { title: 'How to save and delete your status', href: '#st-save-delete-status' },
          { title: 'About status mentions', href: '#st-status-mentions' },
          { title: "Can't create or share status", href: '#st-cant-create-share' },
          { title: "Can't see someone's statuses or replies", href: '#st-cant-see-statuses' },
          { title: 'How to Integrate status with third-party apps', href: '#st-third-party-apps' },
          { title: 'About seeing ads on WhatsApp Status', href: '#st-ads-on-status' },
        ],
      },
    ],
  },
  {
    id: 'chats',
    label: 'Chats',
    icon: 'chat',
    articles: [
      {
        id: 'individual-group-chats',
        title: 'Individual and Group Chats',
        href: '#individual-group-chats',
        icon: 'chat',
        subItems: [
          { title: 'How to reply to a message', href: '#igc-reply-to-message' },
          { title: 'How to delete chats', href: '#igc-delete-chats' },
          { title: 'How to clear chats', href: '#igc-clear-chats' },
          { title: 'How to pin or unpin a chat', href: '#igc-pin-unpin-chat' },
          { title: 'How to edit favorites from the Chats tab', href: '#igc-edit-favorites-chats' },
          { title: 'About lists', href: '#igc-about-lists' },
          { title: 'How to use lists', href: '#igc-use-lists' },
          { title: 'How to use click to chat', href: '#igc-click-to-chat' },
          { title: 'How to delete messages', href: '#igc-delete-messages' },
          { title: 'How to forward messages', href: '#igc-forward-messages' },
          { title: 'About forwarding limits', href: '#igc-forwarding-limits' },
          { title: 'How to pin a message', href: '#igc-pin-message' },
          { title: 'How to star or unstar a message', href: '#igc-star-message' },
          { title: 'How to react to messages', href: '#igc-react-messages' },
          { title: 'How to message yourself', href: '#igc-message-yourself' },
          { title: 'How to format your messages', href: '#igc-format-messages' },
          { title: 'How to change your app or chat theme', href: '#igc-change-theme' },
        ],
      },
      {
        id: 'backup-restore',
        title: 'Back Up and Restore',
        href: '#backup-restore',
        icon: 'download',
        subItems: [
          { title: 'How to back up your chat history', href: '#bur-back-up-history' },
          { title: 'How to restore your chat history', href: '#bur-restore-history' },
          { title: 'How to transfer your chat history', href: '#bur-transfer-history' },
          { title: 'How to move chats from an Android device to an iPhone', href: '#bur-android-to-iphone' },
          { title: 'How to move chats from an iPhone to an Android device', href: '#bur-iphone-to-android' },
          { title: 'About end-to-end encrypted backup', href: '#bur-e2e-backup' },
          { title: 'About Google Account backups', href: '#bur-google-backups' },
          { title: 'How to turn off WhatsApp in your device backup', href: '#bur-turn-off-device-backup' },
        ],
      },
      {
        id: 'chat-notifications',
        title: 'Notifications',
        href: '#chat-notifications',
        icon: 'flag',
        subItems: [
          { title: 'How to manage your notifications', href: '#cnotif-manage-notifications' },
          { title: 'How to manage conversation tones', href: '#cnotif-conversation-tones' },
          { title: 'How to change your ringtone for WhatsApp', href: '#cnotif-ringtone' },
          {
            title: 'How to mute or unmute individual or group chat notifications',
            href: '#cnotif-mute-unmute',
          },
          { title: "Can't see or hear notifications", href: '#cnotif-cant-see-hear' },
          { title: 'Troubleshoot problems with notification badges', href: '#cnotif-badges' },
          { title: "Can't see notification count", href: '#cnotif-cant-see-count' },
        ],
      },
      {
        id: 'chat-media',
        title: 'Media',
        href: '#chat-media',
        icon: 'card',
        subItems: [
          { title: 'How to send media, contacts, or location', href: '#cmed-send-media' },
          { title: 'Finding media files', href: '#cmed-finding-media' },
          { title: 'How to forward media', href: '#cmed-forward-media' },
          { title: 'How to edit photos and videos', href: '#cmed-edit-photos-videos' },
          { title: 'How to stop WhatsApp from saving media to your phone', href: '#cmed-stop-saving' },
          { title: 'How to use stickers', href: '#cmed-stickers' },
          { title: 'How to create and share custom stickers and sticker packs', href: '#cmed-custom-stickers' },
          { title: 'How to create avatars', href: '#cmed-create-avatars' },
          { title: 'How to use avatars', href: '#cmed-use-avatars' },
          { title: 'How to create GIFs', href: '#cmed-create-gifs' },
          { title: 'How to send GIFs', href: '#cmed-send-gifs' },
          { title: 'How to use emoji', href: '#cmed-emoji' },
        ],
      },
      {
        id: 'voice-messages-chats',
        title: 'Voice Messages and Chats',
        href: '#voice-messages-chats',
        icon: 'phone',
        subItems: [
          { title: 'How to send voice messages', href: '#vm-send-voice' },
          { title: 'How to play voice messages', href: '#vm-play-voice' },
          { title: 'How to turn voice message transcripts on or off', href: '#vm-transcripts' },
          { title: 'How to preview a voice message', href: '#vm-preview-voice' },
          { title: 'How to delete voice messages', href: '#vm-delete-voice' },
          { title: 'About voice chat in a group', href: '#vm-about-voice-chat-group' },
          { title: 'How to use voice chat in a group', href: '#vm-use-voice-chat-group' },
        ],
      },
      {
        id: 'video-notes',
        title: 'Video Notes',
        href: '#video-notes',
        icon: 'broadcast',
        subItems: [
          { title: 'About video notes', href: '#vn-about-video-notes' },
          { title: 'How to send video notes', href: '#vn-send-video-notes' },
          { title: 'How to play video notes', href: '#vn-play-video-notes' },
          { title: 'How to preview video notes', href: '#vn-preview-video-notes' },
          { title: 'How to delete a video note', href: '#vn-delete-video-note' },
        ],
      },
      {
        id: 'ai-experiences',
        title: 'AI Experiences',
        href: '#ai-experiences',
        icon: 'users',
        subItems: [
          { title: 'About AI experiences available through WhatsApp', href: '#ai-about-ai-experiences' },
          { title: 'About using AI experiences available through WhatsApp', href: '#ai-using-ai-experiences' },
          { title: 'About Meta AI', href: '#ai-about-meta-ai' },
          { title: 'How to chat with Meta AI', href: '#ai-chat-meta-ai' },
          {
            title: 'How to mention and ask Meta AI in an individual or group chat',
            href: '#ai-mention-meta-ai',
          },
          { title: 'About searching WhatsApp and asking Meta AI', href: '#ai-search-ask-meta-ai' },
          { title: 'How to ask Meta AI in the WhatsApp search bar', href: '#ai-ask-in-search' },
          { title: 'How to create an AI-generated image in WhatsApp', href: '#ai-ai-generated-image' },
        ],
      },
      {
        id: 'chats-troubleshooting',
        title: 'Troubleshooting',
        href: '#chats-troubleshooting',
        icon: 'chat',
        subItems: [
          { title: "Can't send or receive messages", href: '#ct-cant-send-receive' },
          {
            title: 'About "Waiting for this message. This may take a while."',
            href: '#ct-waiting-message-awhile',
          },
          { title: 'Seeing "Waiting for this message. Check your phone."', href: '#ct-waiting-check-phone' },
          { title: 'Fix incorrect timestamps on messages', href: '#ct-timestamps' },
          { title: "Can't remember password for encrypted backup", href: '#ct-backup-password' },
          { title: "Can't back up or restore your chat history", href: '#ct-cant-backup-restore' },
        ],
      },
    ],
  },
  {
    id: 'business',
    label: 'Connect with Businesses',
    icon: 'store',
    articles: [
      {
        id: 'business-message',
        title: 'Message',
        href: '#business-message',
        icon: 'chat',
        subItems: [
          { title: 'About messaging businesses on WhatsApp', href: '#biz-msg-about' },
          { title: 'How to start a chat with a business', href: '#biz-msg-start' },
          { title: 'About business account labels', href: '#biz-msg-labels' },
          { title: "How to block or report a business's messages", href: '#biz-msg-block' },
        ],
      },
      {
        id: 'business-discover',
        title: 'Discover',
        href: '#business-discover',
        icon: 'broadcast',
        subItems: [
          { title: 'About Discover on WhatsApp', href: '#biz-disco-about' },
          { title: 'How to find businesses on Discover', href: '#biz-disco-find' },
          { title: 'About recommendations in Discover', href: '#biz-disco-recommend' },
        ],
      },
      {
        id: 'business-shop',
        title: 'Shop',
        href: '#business-shop',
        icon: 'store',
        subItems: [
          { title: 'About Shops on WhatsApp', href: '#biz-shop-about' },
          { title: 'How to browse and search for products in Shop', href: '#biz-shop-browse' },
          { title: 'How to place an order in Shop', href: '#biz-shop-order' },
        ],
      },
    ],
  },
  {
    id: 'calls',
    label: 'Voice and Video Calls',
    icon: 'phone',
    articles: [
      {
        id: 'video-calls',
        title: 'Video Calls',
        href: '#video-calls',
        icon: 'card',
        subItems: [
          { title: 'How to make a video call', href: '#call-make-video' },
          { title: 'How to make a group video call', href: '#call-group-video' },
          { title: 'How to share your screen', href: '#call-share-screen' },
        ],
      },
      {
        id: 'voice-calls',
        title: 'Voice Calls',
        href: '#voice-calls',
        icon: 'phone',
        subItems: [
          { title: 'How to make a voice call', href: '/help-center/how-to-make-a-voice-call?platform=web' },
          { title: 'How to make a group voice call', href: '#call-voice-group' },
          { title: 'How to switch between voice and video during a call', href: '#call-voice-switch' },
        ],
      },
      {
        id: 'calls-troubleshooting',
        title: 'Troubleshooting',
        href: '#calls-troubleshooting',
        icon: 'chat',
        subItems: [
          { title: "Can't connect to a voice or video call", href: '#call-trouble-connect' },
          { title: 'How to improve call quality', href: '#call-trouble-quality' },
          { title: "Can't see video during a video call", href: '#call-trouble-no-video' },
          { title: "Can't hear the other person during a call", href: '#call-trouble-no-audio' },
        ],
      },
    ],
  },
  {
    id: 'communities',
    label: 'Communities',
    icon: 'users',
    articles: [
      {
        id: 'communities-get-started',
        title: 'Get Started',
        href: '#communities-get-started',
        icon: 'flag',
        subItems: [
          { title: 'About communities on WhatsApp', href: '#com-gs-about' },
          { title: 'How to create a community', href: '#com-gs-create' },
          { title: 'How to add or invite people to a community', href: '#com-gs-invite' },
          { title: 'About announcement groups in communities', href: '#com-gs-announce' },
        ],
      },
      {
        id: 'communities-admin',
        title: 'Admin',
        href: '#communities-admin',
        icon: 'userCircle',
        subItems: [
          { title: 'How to manage a community as an admin', href: '#com-ad-manage' },
          { title: 'How to add or remove community groups', href: '#com-ad-groups' },
          { title: 'How to approve new members (if enabled)', href: '#com-ad-approve' },
          { title: "About a community's settings", href: '#com-ad-settings' },
        ],
      },
      {
        id: 'communities-member',
        title: 'Member',
        href: '#communities-member',
        icon: 'users',
        subItems: [
          { title: 'What members can do in a community', href: '#com-mem-what' },
          { title: 'How to leave a community', href: '#com-mem-leave' },
          { title: 'How to mute or customize community notifications', href: '#com-mem-notify' },
        ],
      },
    ],
  },
  {
    id: 'channels',
    label: 'Channels',
    icon: 'broadcast',
    articles: [
      {
        id: 'channels-get-started',
        title: 'Get Started',
        href: '#channels-get-started',
        icon: 'flag',
        subItems: [
          { title: 'About channels on WhatsApp', href: '#ch-gs-about' },
          { title: 'How to find and follow a channel', href: '#ch-gs-follow' },
          { title: 'How to view channel updates', href: '#ch-gs-updates' },
        ],
      },
      {
        id: 'channel-followers-viewers',
        title: 'Channel Followers and Viewers',
        href: '#channel-followers-viewers',
        icon: 'users',
        subItems: [
          { title: 'About being a channel follower', href: '#ch-fv-follower' },
          { title: 'How to react, vote, and reply to channel updates', href: '#ch-fv-engage' },
          { title: 'About channel notifications', href: '#ch-fv-notify' },
        ],
      },
      {
        id: 'channel-admins',
        title: 'Channel Admins',
        href: '#channel-admins',
        icon: 'userCircle',
        subItems: [
          { title: 'How to create a channel (where available)', href: '#ch-ad-create' },
          { title: 'How to post updates as a channel admin', href: '#ch-ad-post' },
          { title: "About a channel's privacy and reach settings", href: '#ch-ad-privacy' },
        ],
      },
    ],
  },
  {
    id: 'privacy',
    label: 'Privacy, Safety, and Security',
    icon: 'lock',
    articles: [
      {
        id: 'privacy',
        title: 'Privacy',
        href: '#privacy',
        icon: 'lock',
        subItems: [
          { title: 'About privacy on WhatsApp', href: '#priv-about' },
          { title: 'How to set up privacy for last seen, profile photo, and status', href: '#priv-profile' },
          { title: 'About read receipts and blue ticks', href: '#priv-read' },
          { title: 'How to use disappearing messages and view-once', href: '#priv-disappear' },
        ],
      },
      {
        id: 'safety',
        title: 'Safety',
        href: '#safety',
        icon: 'userCircle',
        subItems: [
          { title: 'How to stay safe on WhatsApp', href: '#safe-stay' },
          { title: 'How to block, report, and report spam', href: '#safe-block' },
          { title: "About what you shouldn't share in chats or calls", href: '#safe-share' },
        ],
      },
      {
        id: 'security',
        title: 'Security',
        href: '#security',
        icon: 'lock',
        subItems: [
          { title: 'About end-to-end encryption', href: '#sec-e2e' },
          { title: 'Account security tips', href: '/help-center/account-security-tips' },
          { title: 'About two-step verification', href: '/help-center/about-two-step-verification' },
          { title: 'How to recover a compromised account', href: '/help-center/how-to-recover-compromised-account' },
          { title: "How to protect your account if you lose your phone", href: '/help-center/how-to-protect-your-account' },
        ],
      },
    ],
  },
  {
    id: 'accounts',
    label: 'Accounts and Account Bans',
    icon: 'userCircle',
    articles: [
      {
        id: 'acc-accounts',
        title: 'Accounts',
        href: '#accounts',
        icon: 'user',
        subItems: [
          { title: 'How to request account information', href: '#acc-request-info' },
          { title: 'How to request channels report', href: '#acc-channels-report' },
          { title: 'How to request an ads report', href: '#acc-ads-report' },
          { title: 'About changing phones', href: '/help-center/about-changing-phones' },
          { title: 'How to change your phone number', href: '#acc-change-number-how' },
          { title: 'About changing phone numbers', href: '#acc-about-changing-numbers' },
          { title: "Can't change phone number", href: '#acc-cant-change-number' },
          {
            title: 'About using one WhatsApp account on multiple phones, or with multiple phone numbers',
            href: '#acc-one-account-multiple-phones',
          },
          { title: 'How to delete your account', href: '#acc-delete-account' },
        ],
      },
      {
        id: 'acc-bans',
        title: 'Account Bans',
        href: '#account-bans',
        icon: 'userCircle',
        subItems: [
          { title: 'About account bans', href: '#ban-about' },
          { title: 'About account bans on the WhatsApp Business app', href: '#ban-business-app' },
          { title: 'About ban appeals on the WhatsApp Business Platform', href: '#ban-bsp-appeals' },
          { title: 'About temporarily banned accounts', href: '#ban-temporary' },
          { title: 'After your account is unbanned', href: '#ban-after-unbanned' },
          { title: 'About account bans for previously owned phone numbers', href: '#ban-previous-numbers' },
          { title: 'About account bans for unofficial apps', href: '#ban-unofficial-apps' },
        ],
      },
    ],
  },
  {
    id: 'payments',
    label: 'Payments',
    icon: 'card',
    articles: [
      {
        id: 'pay-setting-up',
        title: 'Setting Up Payments',
        href: '#setting-up-payments',
        icon: 'card',
        subItems: [
          { title: 'Learn more about participating countries', href: '#pay-participating-countries' },
          { title: 'How to pay a business for purchases on WhatsApp', href: '#pay-purchases' },
        ],
      },
      {
        id: 'pay-security',
        title: 'Security and Privacy',
        href: '#payments-security-privacy',
        icon: 'lock',
        subItems: [
          { title: 'About authentication messages', href: '#pay-auth-messages' },
          {
            title: 'How to verify your identity with businesses on WhatsApp',
            href: '#pay-verify-identity',
          },
          { title: 'About two-step verification and payments', href: '#pay-2sv-payments' },
        ],
      },
    ],
  },
  {
    id: 'whatsapp-business',
    label: 'WhatsApp for Business',
    icon: 'store',
    articles: [
      {
        id: 'wab-setting-up-account',
        title: 'Setting Up an Account',
        href: '#wab-setting-up-account',
        icon: 'user',
        subItems: [
          { title: 'About WhatsApp Business products', href: '#wab-about-products' },
          { title: 'About WhatsApp Business', href: '#wab-about-waba' },
          { title: 'How to download the WhatsApp Business app', href: '#wab-download-app' },
          { title: 'How to register for the WhatsApp Business app', href: '#wab-register-app' },
          {
            title: 'About moving between WhatsApp Messenger and the WhatsApp Business app',
            href: '#wab-moving-between-apps',
          },
          {
            title: 'How to move your WhatsApp Messenger account to the WhatsApp Business app',
            href: '#wab-move-messenger-to-business',
          },
          { title: 'About your business profile', href: '#wab-business-profile' },
        ],
      },
      {
        id: 'wab-connecting-customers',
        title: 'Connecting with Customers',
        href: '#wab-connecting-customers',
        icon: 'users',
        subItems: [
          { title: 'About channels on the WhatsApp Business app', href: '#wab-channels-business' },
          { title: 'About communities on the WhatsApp Business app', href: '#wab-communities-business' },
          {
            title: 'How to customize how your business appears in chats with customers',
            href: '#wab-customize-appearance',
          },
          { title: 'How to use quick replies', href: '#wab-quick-replies' },
          { title: 'How to use greeting messages', href: '#wab-greeting-messages' },
          { title: 'How to use labels', href: '#wab-labels' },
          { title: 'How to use away messages', href: '#wab-away-messages' },
        ],
      },
      {
        id: 'wab-business-ai',
        title: 'Business AI Experiences',
        href: '#wab-business-ai-experiences',
        icon: 'broadcast',
        subItems: [
          { title: 'About using Business AI to chat with customers', href: '#wab-ai-chat-customers' },
          { title: 'How to set up Business AI', href: '#wab-ai-setup' },
          { title: 'How to teach Business AI', href: '#wab-ai-teach' },
          { title: 'How to pause or delete Business AI', href: '#wab-ai-pause-delete' },
          { title: 'How to remove Business AI from an individual chat', href: '#wab-ai-remove-chat' },
          { title: 'About Business AI behaviors in chats', href: '#wab-ai-behaviors' },
        ],
      },
      {
        id: 'wab-tools-smarter',
        title: 'Tools to Work Smarter',
        href: '#wab-tools-work-smarter',
        icon: 'chat',
        subItems: [
          {
            title: 'How to use Manus through the WhatsApp Business app',
            href: '#wab-manus',
          },
        ],
      },
      {
        id: 'wab-selling',
        title: 'Selling Products and Services',
        href: '#wab-selling-products-services',
        icon: 'store',
        subItems: [
          {
            title: 'About sharing your WhatsApp Business information with Meta to create ads',
            href: '#wab-sharing-meta-ads',
          },
          { title: 'About catalog', href: '#wab-catalog' },
          { title: 'How to create and maintain a catalog', href: '#wab-catalog-maintain' },
          { title: 'How to create and manage a collection in your catalog', href: '#wab-catalog-collections' },
          { title: 'Sharing catalog links', href: '#wab-catalog-links' },
          { title: 'How to share products or services with customers', href: '#wab-share-products' },
          { title: 'About the WhatsApp Business directory', href: '#wab-directory' },
          { title: 'How to apply to the WhatsApp Business directory', href: '#wab-apply-directory' },
          { title: 'About Shops integration with the WhatsApp Business app', href: '#wab-shops-integration' },
        ],
      },
      {
        id: 'wab-troubleshooting',
        title: 'Troubleshooting',
        href: '#wab-troubleshooting',
        icon: 'flag',
        subItems: [
          { title: 'How to update the WhatsApp Business app', href: '#wab-update-app' },
          { title: "Can't save quick reply", href: '#wab-cant-quick-reply' },
          { title: 'Seeing "Logout is pending"', href: '#wab-logout-pending' },
          { title: 'Issues using catalog', href: '#wab-catalog-issues' },
          {
            title: 'How to delete a phone number from the WhatsApp Business Platform',
            href: '#wab-delete-platform-number',
          },
        ],
      },
      {
        id: 'wab-premium',
        title: 'WhatsApp Premium Features',
        href: '#wab-premium-features',
        icon: 'card',
        subItems: [
          { title: 'About Meta Verified for Business on WhatsApp', href: '#wab-meta-verified-about' },
          {
            title: 'How to subscribe to Meta Verified for Business on WhatsApp',
            href: '#wab-meta-verified-subscribe',
          },
          {
            title: 'About eligibility requirements for Meta Verified for Business on WhatsApp',
            href: '#wab-meta-verified-eligibility',
          },
          {
            title: 'About updating business information in your Meta Verified profile',
            href: '#wab-meta-verified-profile',
          },
          {
            title: 'How to manage your Meta Verified subscription on WhatsApp',
            href: '#wab-meta-verified-manage',
          },
          {
            title: "Can't make payment for Meta Verified for Business on WhatsApp",
            href: '#wab-meta-verified-payment',
          },
        ],
      },
      {
        id: 'wab-platform',
        title: 'WhatsApp Business Platform',
        href: '#wab-business-platform',
        icon: 'store',
        subItems: [
          {
            title: 'How to get started on the WhatsApp Business Platform',
            href: '#wab-platform-get-started',
          },
          { title: 'About WhatsApp Business products', href: '#wab-platform-about-products' },
          {
            title: 'What are Business Solution Providers and how can you work with them?',
            href: '#wab-platform-bsp',
          },
          {
            title: 'Verified account visibility within WhatsApp Discover businesses',
            href: '#wab-platform-discover',
          },
          { title: 'About WhatsApp Flows for businesses', href: '#wab-platform-flows' },
          {
            title: 'About sending voice messages on the WhatsApp Business Platform',
            href: '#wab-platform-voice',
          },
          { title: 'About JioMart order cancellations', href: '#wab-platform-jiomart-cancel' },
          { title: 'How to contact JioMart Customer Care', href: '#wab-platform-jiomart-care' },
        ],
      },
    ],
  },
];

export const popularTopics = [
  {
    id: 'pt-get-started',
    title: 'Get Started',
    description: 'Learn how to get started with using WhatsApp.',
    icon: 'devices',
    href: '/help-center/get-started-web',
  },
  {
    id: 'pt-safety',
    title: 'Safety and Security',
    description: 'Your privacy and security are important. Learn how to stay safe on WhatsApp.',
    icon: 'shield',
    href: '/help-center/safety-security',
  },
  {
    id: 'pt-backup',
    title: 'Back Up or Restore Chats',
    description: 'Learn how to back up and restore your chat history.',
    icon: 'cloud',
    href: '/help-center/backup-restore-chats',
  },
];

export const featuredTopics = [
  {
    id: 'ft-teens',
    title: 'Information for Teens',
    description: 'Learn more about information for teens on WhatsApp.',
    icon: 'teens',
    href: '/help-center/teen-information-center',
  },
  {
    id: 'ft-ads',
    title: 'Ads in Status and Channels',
    description:
      'No ads in personal chats. Your personal messages remain end-to-end encrypted. Learn more.',
    icon: 'ads',
    href: '/help-center/ads-status-channels',
  },
  {
    id: 'ft-business',
    title: 'Business Features',
    description: "Learn about WhatsApp's business solutions and how to get started.",
    icon: 'business',
    href: '/help-center/business-features',
  },
];

export const highlightedArticles = [
  { title: 'About temporarily banned accounts', href: '#banned' },
  { title: 'About two-step verification', href: '#2sv' },
  { title: 'How to restore your chat history', href: '#restore' },
  { title: 'Received verification code without requesting it', href: '/help-center/received-verification-code-without-requesting' },
  { title: 'About ads in WhatsApp Status and Channels', href: '/help-center/ads-status-channels' },
];

export const popularArticlesShort = [
  { title: 'How to make a video call', href: '#video-call' },
  { title: 'How to stay safe on WhatsApp', href: '#stay-safe' },
];

export const helpSiteFooter = {
  columns: [
    {
      title: 'Use WhatsApp',
      links: [
        { label: 'Features', href: '/features' },
        { label: 'WhatsApp Web', href: '#web' },
        { label: 'Download', href: '#download' },
      ],
    },
    {
      title: 'About Us',
      links: [
        { label: 'Business', href: '#business' },
        { label: 'Security', href: '/features/security' },
        { label: 'Privacy & Terms', href: '/privacy' },
      ],
    },
    {
      title: 'Get In Touch',
      links: [
        { label: 'Contact Us', href: '#contact' },
        { label: 'Facebook', href: 'https://www.facebook.com/WhatsApp' },
        { label: 'X (Twitter)', href: 'https://twitter.com/whatsapp' },
      ],
    },
  ],
};
