'use client';

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import HelpCenterCopyLinkButton from '../../Molecules/help-center/HelpCenterCopyLinkButton';

const linkClass =
  'font-semibold text-[#008069] underline decoration-[#008069]/30 underline-offset-2 hover:decoration-[#008069]';
const tabBaseClass =
  'relative inline-flex min-h-[40px] items-center gap-1.5 px-2 pb-2 text-[15px] font-semibold text-[#667781]';
const BASE = '/help-center/about-end-to-end-encrypted-backup';

const tabs = [
  { key: 'android', label: 'Android' },
  { key: 'ios', label: 'iOS' },
];

function PlatformTabs({ platform }) {
  const getClass = (key) => `${tabBaseClass} ${platform === key ? 'text-[#008069]' : ''}`;
  return (
    <div className="mb-5 flex w-full max-w-[180px] border-b border-black/[0.1]" role="tablist" aria-label="Choose platform">
      {tabs.map((tab) => (
        <Link key={tab.key} className={getClass(tab.key)} href={`${BASE}?platform=${tab.key}`} role="tab" aria-selected={platform === tab.key}>
          {tab.label}
          {platform === tab.key ? <span className="absolute bottom-[-1px] left-0 h-[3px] w-full rounded-full bg-[#00a884]" aria-hidden /> : null}
        </Link>
      ))}
    </div>
  );
}

export default function AboutEndToEndEncryptedBackupArticle() {
  const searchParams = useSearchParams();
  const platform = searchParams.get('platform') === 'ios' ? 'ios' : 'android';

  return (
    <article className="px-4 pb-16 pt-6 sm:px-8 sm:pt-8 lg:px-12">
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between sm:pr-2">
        <h1 className="max-w-3xl text-[26px] font-bold leading-tight tracking-tight text-[#111b21] sm:text-[32px]">
          About end-to-end encrypted backup
        </h1>
        <HelpCenterCopyLinkButton />
      </div>

      <PlatformTabs platform={platform} />

      <div className="max-w-3xl text-[16px] leading-7 text-[#3b4a54]">
        <p>
          End-to-end encrypted backup adds an extra layer of protection to your chat backup stored in Google Drive or
          iCloud. Only you can access this backup with your password or 64-digit encryption key.
        </p>

        <section className="mt-8">
          <h2 className="text-[24px] font-bold leading-tight text-[#111b21]">Protecting your backup</h2>
          <p className="mt-3">
            WhatsApp secures your backup with either:
          </p>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 marker:text-[#111b21]">
            <li>A password you create.</li>
            <li>A 64-digit encryption key generated by WhatsApp.</li>
          </ul>
          <p className="mt-3">
            This protection applies to backup content and prevents access by third parties, including WhatsApp.
          </p>
        </section>

        <section className="mt-8 rounded-xl bg-[#f5f6f6] px-5 py-4 text-[15px] leading-6 text-[#111b21]">
          <p className="font-semibold">Notes</p>
          <ul className="mt-2 list-disc space-y-1.5 pl-5">
            <li>You cannot access encrypted backups if you forget both password and key.</li>
            <li>You can reset your password only if you still have access to WhatsApp account.</li>
            <li>Keep your key in a secure place and never share it publicly.</li>
          </ul>
        </section>

        <section className="mt-8">
          <h2 className="text-[24px] font-bold leading-tight text-[#111b21]">Turn on end-to-end encrypted backup</h2>
          <ol className="mt-3 list-decimal space-y-1.5 pl-5 marker:text-[#111b21]">
            <li>Go to Settings &gt; Chats &gt; Chat backup.</li>
            <li>Tap End-to-end encrypted backup.</li>
            <li>Tap Turn on and create a password or use a 64-digit key.</li>
            <li>Tap Create to finish setup.</li>
          </ol>
        </section>

        <section className="mt-8">
          <h2 className="text-[24px] font-bold leading-tight text-[#111b21]">Turn off end-to-end encrypted backups</h2>
          <ol className="mt-3 list-decimal space-y-1.5 pl-5 marker:text-[#111b21]">
            <li>Go to Settings &gt; Chats &gt; Chat backup.</li>
            <li>Tap End-to-end encrypted backup.</li>
            <li>Tap Turn off and confirm.</li>
          </ol>
        </section>

        <section className="mt-8">
          <h2 className="text-[24px] font-bold leading-tight text-[#111b21]">Related resources</h2>
          <ul className="mt-3 list-disc space-y-1.5 pl-5 marker:text-[#111b21]">
            <li>
              <Link className={linkClass} href="/help-center/how-to-back-up-your-chat-history?platform=android">
                How to back up your chat history
              </Link>
            </li>
            <li>
              <Link className={linkClass} href="/help-center/how-to-restore-your-chat-history?platform=android">
                How to restore your chat history
              </Link>
            </li>
            <li>
              <Link className={linkClass} href="/privacy">
                WhatsApp privacy policy
              </Link>
            </li>
          </ul>
        </section>
      </div>
    </article>
  );
}
